import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SatStream",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script async src="https://saturn.tech/widget.js"></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
