import "./globals.css";
import { Inter } from "next/font/google";
// import { MoralisProvider } from "react-moralis";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SatStream",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <MoralisProvider> */}
      <script async src="https://saturn.tech/widget.js"></script>
      <body className={inter.className}>{children}</body>
      {/* </MoralisProvider> */}
    </html>
  );
}
